n = input('Nome do aluno(a): ')
n1 = float(input('Primeira nota: '))
n2 = float(input('Segunda nota:'))
print('------------------------------')
print('Nome do aluno(a):', n)
print('Media entre {:.1f} e {:.1f} é igual a {:.1f}'.format(n1, n2, ((n1 + n2) / 2)))
print('------------------------------')
