n = int(input('Digite o número da tabuada desejada: '))
print(f'---tabuada do {n:^3}---')
print(f'{n:^2} x 1  = {n}')
print(f'{n:^2} x 2  = {(n * 2)}')
print(f'{n:^2} x 3  = {(n * 3)}')
print(f'{n:^2} x 4  = {(n * 4)}')
print(f'{n:^2} x 5  = {(n * 5)}')
print(f'{n:^2} x 6  = {(n * 6)}')
print(f'{n:^2} x 7  = {(n * 7)}')
print(f'{n:^2} x 8  = {(n * 8)}')
print(f'{n:^2} x 9  = {(n * 9)}')
print(f'{n:^2} x 10 = {(n * 10)}')
print('--------------------')
